/* AUTOGENERATED, DO NOT EDIT DIRECTLY */
/* UTILS_SKIP */

/**
 * @typedef {Object} UtilityMap
 * @property {string} cTrueBlackRgb
 * @property {string} cTrueBlack
 * @property {string} cBlackRgb
 * @property {string} cBlack
 * @property {string} cGreyDarkRgb
 * @property {string} cGreyDark
 * @property {string} cGreyMidRgb
 * @property {string} cGreyMid
 * @property {string} cGreyRgb
 * @property {string} cGrey
 * @property {string} cGreenRgb
 * @property {string} cGreen
 * @property {string} cGreenLimeRgb
 * @property {string} cGreenLime
 * @property {string} cGreenLimeLightRgb
 * @property {string} cGreenLimeLight
 * @property {string} cGreenLightRgb
 * @property {string} cGreenLight
 * @property {string} cGreenLightestRgb
 * @property {string} cGreenLightest
 * @property {string} cGreyGreenLightRgb
 * @property {string} cGreyGreenLight
 * @property {string} cGreyLightRgb
 * @property {string} cGreyLight
 * @property {string} cGreyLightNeutralRgb
 * @property {string} cGreyLightNeutral
 * @property {string} cWhiteRgb
 * @property {string} cWhite
 * @property {string} cSkillMatchGreenDarkRgb
 * @property {string} cSkillMatchGreenDark
 * @property {string} cSkillMatchGreenRgb
 * @property {string} cSkillMatchGreen
 * @property {string} cSkillMatchGreenLightRgb
 * @property {string} cSkillMatchGreenLight
 * @property {string} cYellowRgb
 * @property {string} cYellow
 * @property {string} cPurpleRgb
 * @property {string} cPurple
 * @property {string} cRedRgb
 * @property {string} cRed
 * @property {string} cGreenAlpha40
 * @property {string} cGreenAlpha5
 * @property {string} cBlackAlpha10
 * @property {string} cGrayGmacLight1Rgb
 * @property {string} cGrayGmacLight2Rgb
 * @property {string} cGrayGmacLight3Rgb
 * @property {string} cGrayGmacLight1
 * @property {string} cGrayGmacLight2
 * @property {string} cGrayGmacLight3
 * @property {string} cGmacBlackRgb
 * @property {string} cGmacBlack
 * @property {string} cGmacBlackDarkRgb
 * @property {string} cGmacBlackDark
 * @property {string} cGmacWhiteRgb
 * @property {string} cGmacWhite
 * @property {string} cGreenGmacRgb
 * @property {string} cGreenGmac
 * @property {string} cCyanGmacRgb
 * @property {string} cCyanGmac
 * @property {string} cRedGmacRgb
 * @property {string} cRedGmac
 * @property {string} cLilacGmacRgb
 * @property {string} cLilacGmac
 * @property {string} cSteelBlueGmacRgb
 * @property {string} cSteelBlueGmac
 * @property {string} cPeriwinkleGmacRgb
 * @property {string} cPeriwinkleGmac
 * @property {string} cGrayGmacRgb
 * @property {string} cGrayGmac
 * @property {string} cGrayGmacAlpha90
 * @property {string} cGrayGmacAlpha20
 * @property {string} cGrayGmacAlpha15
 * @property {string} cBorderDefault
 * @property {string} cInputBorder
 */

/**
 * @type {UtilityMap}
 */
export const u = new Proxy({}, {
  get: (_, prop) => {
    return prop;
  }
});